### ISSUE TITLE
Easier CLI installation and use

### ISSUE THREAD

**Issue by nvuillam** [darkriszty/MarkdownTablePrettify-VSCodeExt#49]
Hi, I'm currently trying to integrate MarkdownTablePrettify in [Mega-Linter](https://nvuillam.github.io/mega-linter/)

I follow the instructions for CLI use, but as it is used on a alpine linux based image, I would like to avoid to have to install typescript just to compile

Would it be possible to deliver MarkdownTablePrettify as a simple npm package, with ts files already compiled in js ?
It could be done with a Github action for example :)

**Comment by darkriszty** [comment]
Hi @nvuillam!

There weren't really any use cases or requests so far to do this, but I could create an npm package out of it 🙂 I hope to get a chance to work the details out sometime in January and publish it on the npm registry.

Thanks for the suggestion 👍

**Comment by nvuillam** [comment]
That's great,  thanks a lot, I'll keep a look on this issue to see what's new :)

**Comment by darkriszty** [comment]
Hi, I started working on a version by taking the typescript code and compiling it down to ES5 to be shipped inside the npm package. 

It currently exposes the entry point that's also used by the _CLI_. The npm package then could be very simply used from regular NodeJS or web apps.

Would this also cover your use case in Mega-Linter?

```JS
import { CliPrettify } from 'markdown-table-prettify';
// or
const { CliPrettify } = require('markdown-table-prettify');

console.log(CliPrettify.prettify(
`hello|world
-|-
foo|bar`));

/* Output:
hello | world
------|------
foo   | bar
*/
```

**Comment by nvuillam** [comment]
If I can call it via command line, it covers the case :) 
If i can call it with a list of files, it's even better ^^

Example:

`markdown-table-prettify some_folder/file1.md another_folder/file2.md changelog.md`

**Comment by nvuillam** [comment]
And if as a bonus, there could be a --check option to return 1 if there are wrongly formatted tables, it's the best :)

**Comment by darkriszty** [comment]
You should be able to call it from the command line easily with  `npx`. If you prefer not to use `npx`, then just use one of the scripts from `node_modules/.bin/markdown-table-prettify*`.

Currently I'm not planning to change the way the CLI input is implemented to accept a list of files, I hope that's okay. Maybe you could start from something like this: `cat some_folder/file1.md file2.md | npx markdown-table-prettify`, but I imagine that your use case is a bit more complex and would require some more scripts around it. The `--check` flag is also available and behaves the same way as the `npm run check-md` described in the readme.

The NPM package is published at https://www.npmjs.com/package/markdown-table-prettify
Please give it a try and let me know if you have issues🙂

**Comment by nvuillam** [comment]
That's great, I'll have a look tonight and provide you feedback :)

**Comment by nvuillam** [comment]
mmm there is an infinite loop i think


To reproduce (on windows)

```shell
npm i markdown-table-prettify -g
markdown-table-prettify markdown_bad_1.md
```

markdown_bad_1.md content:

```markdown
## Bad Markdown

This is just standard good markdown.

###### Second level header

This header does **NOT** follow the __step__ down from `level 1`.

- Here it *is*
  - Some more indention
      - why so much?

```
ls -la
```

| this | is a wrong | table |
| ---------------| -----------| -----------|
| hahaha | naaaaaaah | wrong formatting !    |
| hahaha | naaaaaaah | wrong formatting !    |

# Walk away

We're all done **here**.
- [Link Action]https://github.com
- [Link Action 2](#wesh)
- [Link Action 3](http://www.glouglouglglsdgdfgfdgsfgdfgdf.com)
```

**Comment by nvuillam** [comment]
(and the same happens with `markdown-table-prettify --check markdown_bad_1.md`

**Comment by nvuillam** [comment]
And if you could implement `markdown-table-prettify --version` and `markdown-table-prettify --help` it would be great :) ( but i can do without)

**Comment by darkriszty** [comment]
The CLI is not implemented to accept file(s) as argument, you need to feed in the _contents_ of the file to `stdin`: `npx markdown-table-prettify < input.md` (note the `<`). I have no problem when formatting your `markdown_bad_1.md` example.

I'm not planning to add a check for version or help at the moment, as you can get the version either from the `package.json` file where you installed it or via `npm list` when it's installed globally (on windows: `npm list -g --depth=0 | find "markdown-table-prettify"`), while I'm trying to keep the documentation info in the README.md file (I'll still need to mention the `--check` for the NPM version) 🙂

**Comment by nvuillam** [comment]
ouch... i can manage without the help and the version, but without the file as parameter i can't ... :/
Can't you just add so fs.read / fs.write if you have a file ?
It's almost unusable out of the box without that :/

**Comment by darkriszty** [comment]
This was always how the CLI part worked, even before I packaged it now into an NPM package. I want to avoid reading and writing files, as it opens the flood gate for new switches and new error cases. Just to name a few of many possibilities for switches: accept file name(s) or directory name(s), to save or not save the files to disk, to be able to provide new file names or directory names instead of overwriting the existing ones, etc. I'm trying to keep this as a small utility app and dedicate my time to the formatting features instead, as I think that all of the above could be achieved either by piping through other commands or writing small custom scripts.  

Here are just a couple of examples; you can feed multiple files into it as input and you can even save the result to new files 🙂 

```sh
# feed multiple files as input
$ cat some_folder/file1.md file2.md | npx markdown-table-prettify

# save the output to new files
$ find . -name '*.md' -exec sh -c 'npx markdown-table-prettify < ${0} > ${0}.new' {} \; 
```

**Comment by nvuillam** [comment]
There is not a single linter that works like that in all the ones I manage in Mega-Linter, and I'm afraid with a call that complicated it wouldn't push away others than me...
That would be sad because in these documentation-as-code times, I really think there is a need for a markdown-table-prettifier !

On a last resort, would you be offended if I hard-forked your repo to make the CLI usable by any "basic user" ?

**Comment by darkriszty** [comment]
Since this is a formatter, I think that keeping it simple (getting markdown input, producing markdown output) is exactly what it's supposed to do, as the usage can vary from app to app that it's being used in. So bash scripts are not mandatory (even for CLI), it's based on how one wants to use it. 

If you prefer not to use any bash scripts, I would recommend that you use the npm package you requested in this issue and do your own logic in a small NodeJS app. But if you prefer to fork the repo instead, that's also fine with me, the license is permissive :slightly_smiling_face:

**Comment by nvuillam** [comment]
All the formatters I know can take a file as input :'(
Are you sure you don't want to manage that ? I can do the fork but I don't really have the time 😢

**Comment by darkriszty** [comment]
I would like to avoid having to read/write files in this repository. Besides the reasons that I already elaborated above, as it's now both a VSCode extension and an npm package usable in web apps, messing with files could create security suspicions or uncertainties. 

If you really prefer to use it with file names instead of stdin, my previous suggestion would be the best: create a small NodeJS app and install this one as an npm package. Otherwise you can also make a fork. 

Please feel free to report new issues in the future and good luck with Mega-Linter 🙂 🍀

**Comment by nvuillam** [comment]
Ok i'll go for the npm package embedding your npm package ! :)

Thanks for your assistance :)

**Comment by nvuillam** [comment]
Work in progress :) 
https://github.com/nvuillam/markdown-table-formatter

(not working yet ^^ )

**Comment by nvuillam** [comment]
Working and integrated into Mega-Linter :) 

Thanks again for your package !

https://nvuillam.github.io/mega-linter/descriptors/markdown_markdown_table_formatter/
