### ISSUE TITLE
Emoji's cause misalignment 

### ISSUE THREAD

**Issue by cln-io** [darkriszty/MarkdownTablePrettify-VSCodeExt#66]
Hi,

When I'm using emojis inside of a table, for example, flags
It seems spacing is getting thrown off

eg:

No prettify done
```
|Date|Flag|Person|
|-----|-----|-------|
| 2022-04-04 |  🇳🇱 / 🇩🇪  | Bob |
| 2022-04-04 |  🇳🇱 / 🇩🇪  / 🇩🇪  / 🇩🇪  / 🇩🇪  / 🇩🇪 | Bob |
```

Prettify done

```
|Date|Flag|Person|
|-----|-----|-------|
| 2022-04-04 |               🇳🇱 / 🇩🇪                  | Bob | <---------------- output
| 2022-04-04 |  🇳🇱 / 🇩🇪  / 🇩🇪  / 🇩🇪  / 🇩🇪  / 🇩🇪 | Bob |
| 2022-04-04 |               🇳🇱 / 🇩🇪           | Bob | <----------------------- expected
```

It's off only a couple of spaces,

**Comment by darkriszty** [comment]
Hi and thanks for reporting. This is a known issue of this project and it's being tracked in #4 (also mentioned in the readme), and it's not something I actually expect to be fixed any time soon. That is because the extension already has support for a limited number of CJK characters, but it is quite complicated to get right for all Unicode characters (including emojis) with different widths and with different VsCode fonts, including monospaced and non-monospaced ones.
